### ISSUE TITLE
BUILD FAILED

### ISSUE THREAD

**Issue by KamilSJaron** [marbl/MHAP#10]
On OS X Yosemite with java version "1.8.0_60", javac -version
javac 1.6.0_65 and Apache Ant(TM) version 1.9.6 compiled on June 29 2015. 

I have not found the compiler output for details (if you write me, where can I find it, I can add it).
log:

Buildfile: /Users/kjaron/Documents/PacBio/MHAP/MHAP/build.xml

clean:
   [delete] Deleting directory /Users/kjaron/Documents/PacBio/MHAP/MHAP/target

init:
     [echo] -------- MHAP 1.6 --------
    [mkdir] Created dir: /Users/kjaron/Documents/PacBio/MHAP/MHAP/target
    [mkdir] Created dir: /Users/kjaron/Documents/PacBio/MHAP/MHAP/target/classes
    [mkdir] Created dir: /Users/kjaron/Documents/PacBio/MHAP/MHAP/target/classes/bin
    [mkdir] Created dir: /Users/kjaron/Documents/PacBio/MHAP/MHAP/target/classes/properties
    [mkdir] Created dir: /Users/kjaron/Documents/PacBio/MHAP/MHAP/target/test-classes
     [copy] Copying 1 file to /Users/kjaron/Documents/PacBio/MHAP/MHAP/target/classes

copy-lib:
    [mkdir] Created dir: /Users/kjaron/Documents/PacBio/MHAP/MHAP/target/lib
     [copy] Copying 4 files to /Users/kjaron/Documents/PacBio/MHAP/MHAP/target/lib

buildinfo:
[propertyfile] Creating new property file: /Users/kjaron/Documents/PacBio/MHAP/MHAP/target/classes/properties/mhap.properties

compile:
    [javac] Compiling 56 source files to /Users/kjaron/Documents/PacBio/MHAP/MHAP/target/classes
    [javac] javac: invalid target release: 1.8
    [javac] Usage: javac <options> <source files>
    [javac] use -help for a list of possible options

BUILD FAILED
/Users/kjaron/Documents/PacBio/MHAP/MHAP/build.xml:155: Compile failed; see the compiler error output for details.

Total time: 0 seconds

**Comment by skoren** [comment]
It looks like you have a newer JRE (java -version of 1.8) but your JDK which is used to compile the program is older (javac -version of 1.6) which is the cause of the error. You should have JDK 1.8 to build the software so both java and javac should report version 1.8. 

Since you have the latest JRE, you should be able to use the pre-compiled distribution and run it on your system.

**Comment by KamilSJaron** [comment]
Great, thanks! Pre-compiled version seems to be working. 

Should I try to update my java compiler to find if that was the issue, or it is not important for you?
