### ISSUE TITLE
Retrieving link between input and output sequences 

### ISSUE THREAD

**Issue by chklopp** [marbl/MHAP#11]
Hi,

Could MHAP produce a file linking input and output read names?

Cheers,

Christophe

**Comment by konstantinberlin** [comment]
Are you talking about when using binary files vs. text files as input?

**Comment by chklopp** [comment]
No, I would like to have the correspondence between corrected and input reads.

**Comment by konstantinberlin** [comment]
MHAP doesn't do correction, it is an overlapper only. Are you talking about PBcR or CANU? In that case you should submit that issue there.

**Comment by chklopp** [comment]
PBcR.

**Comment by konstantinberlin** [comment]
Ok great.
