### ISSUE TITLE
Installation problem. 

### ISSUE THREAD

**Issue by saadabrar12** [marbl/MHAP#16]
I tried installing MHAP. But once i mount into the folder and run maven install it shows the following command. Could you please help.

saad@Mercenary:~/MHAP$ maven install
No command 'maven' found, did you mean:
 Command 'aven' from package 'survex-aven' (universe)
maven: command not found

**Comment by skoren** [comment]
Maven is a build package, similar to autoconf for Java. You can download it from here:
https://maven.apache.org

If you are only interested in running MHAP, not developing the code, you can also download the pre-build jar files which only required the JVM to run. The instructions for using them are on the documentations page:
http://mhap.readthedocs.io/en/latest/installation.html
Under the pre-compiled section. Once you download and extract, you can follow the quick-start instructions:
http://mhap.readthedocs.io/en/latest/quickstart.html
