### ISSUE TITLE
out of memory error

### ISSUE THREAD

**Issue by miladPrivates** [marbl/MHAP#19]
hi, thanks for your implementation.
I run the jar file with below command for finding yeast reads' overlaps:
`java -Xmx32g -server -jar mhap-2.1.1.jar -s yeast_filtered.fa`
but after some minutes, this error occurred:
> Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap.<init>(Int2ObjectOpe                                                      nHashMap.java:126)
        at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap.<init>(Int2ObjectOpe                                                      nHashMap.java:136)
        at edu.umd.marbl.mhap.impl.MinHashSearch.<init>(MinHashSearch.java:89)
        at edu.umd.marbl.mhap.main.MhapMain.getMatchSearch(MhapMain.java:550)
        at edu.umd.marbl.mhap.main.MhapMain.computeMain(MhapMain.java:454)
        at edu.umd.marbl.mhap.main.MhapMain.main(MhapMain.java:313)

this error occurred after 460000 sequences loaded and processed ( when this line printed in the output: `Current # sequences loaded and processed from file: 460000...
`)

1. may you help me to find the reason for this error? 
2. am I choosing the right command for finding overlaps?
3. how can I solve that error?

thanks.

**Comment by skoren** [comment]
Your command is ok but you’ll have to increase the memory over 32g. We typically chunk the dataset and compare all reads against each partition.  This will limit your memory since the chunks are smaller. See the Canu code for examples of this chunking. You could also run Canu to get your overlaps.

**Comment by miladPrivates** [comment]
how to know the total number of sequences (which stopped at #460000 for me)?
I want to know how much work left.

**Comment by skoren** [comment]
That’s based on the number of reads in your input, how many input reads do you have? Can’t tell from your log snippet but I’d guess it’s still loading all the reads into memory and indexing. No overlaps were computed yet.

**Comment by miladPrivates** [comment]
thanks, finally how can i change the chunk size manually in the MHAP code?

**Comment by skoren** [comment]
There is no automated chunking support, it is dependent on the user to chunk the input fasta file themselves. If you don't want to do it yourself, I recommend using Canu as the wrapper which will do the chunking for you and run overlapper.

**Comment by miladPrivates** [comment]
thank u so much.
